### ISSUE TITLE
Todo: Create experiment task specification document template

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/task-mapping#1]
Eventually, we're going to need something to give to Nicholas's team that contains everything they need to implement the experiment. A standardized format for this would help Nicholas, and may also be something that we have a turker or another outsourced worker complete. 

These documents are likely also to serve as documentation for how we implemented the task when we publish our work, and will serve as reference for other people wishing to implement the task or understand how we did so.

**Comment by amaatouq** [comment]
There is one here: https://docs.google.com/document/d/19SJTHJJhuBDPsMB8becTiCGQE6dhGxIE165Gz-NNBf4/edit?usp=sharing

**Comment by markwhiting** [comment]
Notably both our task mapping efforts and task implementation / experimentation efforts require a description of each task. I think we had originally thought those might be roughly interchangeable but I'm not sure if thats actually true.
