### ISSUE TITLE
Double check formatting and clarity of mapped tasks

### ISSUE THREAD

**Issue by markwhiting** [Watts-Lab/task-mapping#266]
One or multiple people should read and check every task for: 

- [ ] **correct image tagging** — local tags, locally stored images, and correct path
- [ ] **correct formatting** — removing erroneous block quoting and make sure MD lists are showing up correctly
- [ ] **content completion** — marking anything that has clear issues, e.g., a missing section or an incomplete section, and correcting anything that should be different, e.g., spelling and grammar mistakes.

**Comment by xehu** [comment]
Building these questions into the auditing process and new assignment, [here](https://docs.google.com/document/d/103v4l8PbxVkh7I8PMLzujnaYhS3wF809seoVW6dR7hw/edit)!
