### ISSUE TITLE
Plan workshop

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/task-mapping#311]
Once #310 is done, we'll have a time for the workshop.
- [ ] Slides for workshop
- [ ] Overall planned activities for the time we have

**Comment by amaatouq** [comment]
Initial thoughts: I am thinking the workshop will have 2 or 3 major activities:
- Project overview: presenting something similar to my talk at DataColada, but emphasizing the importance of task mapping and implementation for the overall success of the project. 
- New mapping procedure:
  - Announcing the assignment: Describing their research activities and how they can contribute to the design of the instrument (e.g., reading the papers, extracting dimensions, coming up with questions, extracting relevant excerpts and examples for each dimension).
  - Presenting them with the new process for labeling (Github issues/discussions, confidence, task cleaning).
- Task implementation (?): Perhaps we get Shawn and Dawn to present the template for task implementation. Also, any questions or thoughts task implementers may have?
